/**
 * HavenBridgeJNI.c
 *
 * JNI glue between Kotlin HavenBridge and Go C-exported functions.
 * Each function converts JNI types (jstring) to C types (char*),
 * calls the corresponding Go export, and converts the result back.
 *
 * The Go exports are declared in the haven.h generated by `go build -buildmode=c-shared`.
 */

#include <jni.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <pthread.h>
#include <android/log.h>

// ---- Stderr-to-logcat redirect ----
// Go's log.Printf() writes to stderr, which Android discards by default.
// This pipes stderr output to logcat so we can see Go relay logs.
static int sLogPipe[2];
static volatile int sLogRedirected = 0;

static void *logReaderThread(void *arg) {
    char buf[1024];
    ssize_t n;
    while ((n = read(sLogPipe[0], buf, sizeof(buf) - 1)) > 0) {
        buf[n] = '\0';
        // Trim trailing newlines
        while (n > 0 && (buf[n-1] == '\n' || buf[n-1] == '\r')) {
            buf[--n] = '\0';
        }
        if (n > 0) {
            __android_log_print(ANDROID_LOG_DEBUG, "GoRelay", "%s", buf);
        }
    }
    return NULL;
}

static void ensureStderrToLogcat(void) {
    if (sLogRedirected) return;
    sLogRedirected = 1;

    setvbuf(stderr, NULL, _IOLBF, 0);
    if (pipe(sLogPipe) == -1) return;
    dup2(sLogPipe[1], STDERR_FILENO);

    pthread_t thr;
    pthread_create(&thr, NULL, logReaderThread, NULL);
    pthread_detach(thr);
}

// Go C-exported function declarations (from cshared.go)
extern void SetHavenEnvC(const char* key, const char* value);
extern void StartRelayC(int importMode);
extern void StopRelayC(void);
extern void RequestRelaySyncC(void);
extern int BackupDatabaseC(const char* outputPath);
extern int RestoreDatabaseC(const char* inputPath);
extern int BackupToCloudC(void);
extern int RestoreFromCloudC(void);
extern int ZipDirectoryC(const char* dirPath, const char* zipPath);
extern int UnzipDirectoryC(const char* zipPath, const char* destPath);
extern char* SignEventC(const char* jsonStr, const char* sk);
extern char* MineAndSignEventC(const char* jsonStr, const char* sk, int difficulty, int maxAttempts);
extern char* GenerateKeyPairC(void);
extern char* GetPublicKeyC(const char* sk);
extern char* EncryptNIP04C(const char* plaintext, const char* pubkey, const char* privkey);
extern char* DecryptNIP04C(const char* ciphertext, const char* pubkey, const char* privkey);
extern char* EncryptNIP44C(const char* plaintext, const char* pubkey, const char* privkey);
extern char* DecryptNIP44C(const char* ciphertext, const char* pubkey, const char* privkey);
extern char* EncryptNIP49C(const char* nsecHex, const char* password);
extern char* DecryptNIP49C(const char* ncryptsec, const char* password);
extern char* DeriveTaprootAddressC(const char* hexPubKey);
extern char* FetchFeeEstimatesC(void);
extern char* SweepToAddressC(const char* nsecHex, const char* destAddr, int feeRate);
extern char* NIP46ConnectC(const char* clientSK, const char* bunkerURL);
extern void NIP46DisconnectC(void);
extern char* NIP46SignEventC(const char* eventJSON);
extern char* NIP46GetPublicKeyC(void);
extern char* NIP46NIP44EncryptC(const char* targetPubkey, const char* plaintext);
extern char* NIP46NIP44DecryptC(const char* targetPubkey, const char* ciphertext);
extern char* NIP46NIP04EncryptC(const char* targetPubkey, const char* plaintext);
extern char* NIP46NIP04DecryptC(const char* targetPubkey, const char* ciphertext);
extern int NIP46PingC(void);
extern char* NIP46GetPendingAuthURLC(void);
extern char* ComputePopularNotesC(void);
extern char* GetImportLogC(void);
extern char* GetNotifyLogC(void);

// Helper: Convert Go C.CString result to jstring (and free the C memory)
static jstring goStringToJstring(JNIEnv *env, char *goStr) {
    if (goStr == NULL) return NULL;
    jstring result = (*env)->NewStringUTF(env, goStr);
    free(goStr);
    return result;
}

// Helper: Convert jstring to const char* (caller must ReleaseStringUTFChars)
#define GET_CSTR(env, jstr) ((jstr) ? (*env)->GetStringUTFChars(env, jstr, NULL) : NULL)
#define REL_CSTR(env, jstr, cstr) do { if (jstr && cstr) (*env)->ReleaseStringUTFChars(env, jstr, cstr); } while(0)

// ---- Relay lifecycle ----

JNIEXPORT void JNICALL
Java_com_nostrvault_relay_HavenBridge_setEnv(JNIEnv *env, jobject thiz, jstring key, jstring value) {
    const char *cKey = GET_CSTR(env, key);
    const char *cVal = GET_CSTR(env, value);
    SetHavenEnvC((char*)cKey, (char*)cVal);
    REL_CSTR(env, key, cKey);
    REL_CSTR(env, value, cVal);
}

JNIEXPORT void JNICALL
Java_com_nostrvault_relay_HavenBridge_startRelay(JNIEnv *env, jobject thiz, jboolean importMode) {
    ensureStderrToLogcat();
    StartRelayC(importMode ? 1 : 0);
}

JNIEXPORT void JNICALL
Java_com_nostrvault_relay_HavenBridge_stopRelay(JNIEnv *env, jobject thiz) {
    StopRelayC();
}

JNIEXPORT void JNICALL
Java_com_nostrvault_relay_HavenBridge_requestRelaySync(JNIEnv *env, jobject thiz) {
    RequestRelaySyncC();
}

// ---- Database operations ----

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_backupDatabase(JNIEnv *env, jobject thiz, jstring outputPath) {
    const char *cPath = GET_CSTR(env, outputPath);
    int result = BackupDatabaseC((char*)cPath);
    REL_CSTR(env, outputPath, cPath);
    return result;
}

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_restoreDatabase(JNIEnv *env, jobject thiz, jstring inputPath) {
    const char *cPath = GET_CSTR(env, inputPath);
    int result = RestoreDatabaseC((char*)cPath);
    REL_CSTR(env, inputPath, cPath);
    return result;
}

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_backupToCloud(JNIEnv *env, jobject thiz) {
    return BackupToCloudC();
}

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_restoreFromCloud(JNIEnv *env, jobject thiz) {
    return RestoreFromCloudC();
}

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_zipDirectory(JNIEnv *env, jobject thiz, jstring dirPath, jstring zipPath) {
    const char *cDir = GET_CSTR(env, dirPath);
    const char *cZip = GET_CSTR(env, zipPath);
    int result = ZipDirectoryC((char*)cDir, (char*)cZip);
    REL_CSTR(env, dirPath, cDir);
    REL_CSTR(env, zipPath, cZip);
    return result;
}

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_unzipDirectory(JNIEnv *env, jobject thiz, jstring zipPath, jstring destPath) {
    const char *cZip = GET_CSTR(env, zipPath);
    const char *cDest = GET_CSTR(env, destPath);
    int result = UnzipDirectoryC((char*)cZip, (char*)cDest);
    REL_CSTR(env, zipPath, cZip);
    REL_CSTR(env, destPath, cDest);
    return result;
}

// ---- Cryptographic operations ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_signEvent(JNIEnv *env, jobject thiz, jstring eventJson, jstring secretKeyHex) {
    const char *cJson = GET_CSTR(env, eventJson);
    const char *cSk = GET_CSTR(env, secretKeyHex);
    char *result = SignEventC((char*)cJson, (char*)cSk);
    REL_CSTR(env, eventJson, cJson);
    REL_CSTR(env, secretKeyHex, cSk);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_mineAndSignEvent(JNIEnv *env, jobject thiz,
        jstring eventJson, jstring secretKeyHex, jint difficulty, jint maxAttempts) {
    const char *cJson = GET_CSTR(env, eventJson);
    const char *cSk = GET_CSTR(env, secretKeyHex);
    char *result = MineAndSignEventC((char*)cJson, (char*)cSk, difficulty, maxAttempts);
    REL_CSTR(env, eventJson, cJson);
    REL_CSTR(env, secretKeyHex, cSk);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_generateKeyPair(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, GenerateKeyPairC());
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_getPublicKey(JNIEnv *env, jobject thiz, jstring secretKeyHex) {
    const char *cSk = GET_CSTR(env, secretKeyHex);
    char *result = GetPublicKeyC((char*)cSk);
    REL_CSTR(env, secretKeyHex, cSk);
    return goStringToJstring(env, result);
}

// ---- NIP-04 ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_encryptNIP04(JNIEnv *env, jobject thiz,
        jstring plaintext, jstring pubkey, jstring privkey) {
    const char *cPt = GET_CSTR(env, plaintext);
    const char *cPub = GET_CSTR(env, pubkey);
    const char *cPriv = GET_CSTR(env, privkey);
    char *result = EncryptNIP04C((char*)cPt, (char*)cPub, (char*)cPriv);
    REL_CSTR(env, plaintext, cPt);
    REL_CSTR(env, pubkey, cPub);
    REL_CSTR(env, privkey, cPriv);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_decryptNIP04(JNIEnv *env, jobject thiz,
        jstring ciphertext, jstring pubkey, jstring privkey) {
    const char *cCt = GET_CSTR(env, ciphertext);
    const char *cPub = GET_CSTR(env, pubkey);
    const char *cPriv = GET_CSTR(env, privkey);
    char *result = DecryptNIP04C((char*)cCt, (char*)cPub, (char*)cPriv);
    REL_CSTR(env, ciphertext, cCt);
    REL_CSTR(env, pubkey, cPub);
    REL_CSTR(env, privkey, cPriv);
    return goStringToJstring(env, result);
}

// ---- NIP-44 ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_encryptNIP44(JNIEnv *env, jobject thiz,
        jstring plaintext, jstring pubkey, jstring privkey) {
    const char *cPt = GET_CSTR(env, plaintext);
    const char *cPub = GET_CSTR(env, pubkey);
    const char *cPriv = GET_CSTR(env, privkey);
    char *result = EncryptNIP44C((char*)cPt, (char*)cPub, (char*)cPriv);
    REL_CSTR(env, plaintext, cPt);
    REL_CSTR(env, pubkey, cPub);
    REL_CSTR(env, privkey, cPriv);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_decryptNIP44(JNIEnv *env, jobject thiz,
        jstring ciphertext, jstring pubkey, jstring privkey) {
    const char *cCt = GET_CSTR(env, ciphertext);
    const char *cPub = GET_CSTR(env, pubkey);
    const char *cPriv = GET_CSTR(env, privkey);
    char *result = DecryptNIP44C((char*)cCt, (char*)cPub, (char*)cPriv);
    REL_CSTR(env, ciphertext, cCt);
    REL_CSTR(env, pubkey, cPub);
    REL_CSTR(env, privkey, cPriv);
    return goStringToJstring(env, result);
}

// ---- NIP-49 ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_encryptNIP49(JNIEnv *env, jobject thiz,
        jstring nsecHex, jstring password) {
    const char *cNsec = GET_CSTR(env, nsecHex);
    const char *cPw = GET_CSTR(env, password);
    char *result = EncryptNIP49C((char*)cNsec, (char*)cPw);
    REL_CSTR(env, nsecHex, cNsec);
    REL_CSTR(env, password, cPw);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_decryptNIP49(JNIEnv *env, jobject thiz,
        jstring ncryptsec, jstring password) {
    const char *cNc = GET_CSTR(env, ncryptsec);
    const char *cPw = GET_CSTR(env, password);
    char *result = DecryptNIP49C((char*)cNc, (char*)cPw);
    REL_CSTR(env, ncryptsec, cNc);
    REL_CSTR(env, password, cPw);
    return goStringToJstring(env, result);
}

// ---- Bitcoin / Taproot ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_deriveTaprootAddress(JNIEnv *env, jobject thiz, jstring hexPubKey) {
    const char *cPk = GET_CSTR(env, hexPubKey);
    char *result = DeriveTaprootAddressC((char*)cPk);
    REL_CSTR(env, hexPubKey, cPk);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_fetchFeeEstimates(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, FetchFeeEstimatesC());
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_sweepToAddress(JNIEnv *env, jobject thiz,
        jstring nsecHex, jstring destAddr, jint feeRate) {
    const char *cNsec = GET_CSTR(env, nsecHex);
    const char *cAddr = GET_CSTR(env, destAddr);
    char *result = SweepToAddressC((char*)cNsec, (char*)cAddr, feeRate);
    REL_CSTR(env, nsecHex, cNsec);
    REL_CSTR(env, destAddr, cAddr);
    return goStringToJstring(env, result);
}

// ---- NIP-46 Remote Signer ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46Connect(JNIEnv *env, jobject thiz,
        jstring clientSecretKey, jstring bunkerUrl) {
    const char *cSk = GET_CSTR(env, clientSecretKey);
    const char *cUrl = GET_CSTR(env, bunkerUrl);
    char *result = NIP46ConnectC((char*)cSk, (char*)cUrl);
    REL_CSTR(env, clientSecretKey, cSk);
    REL_CSTR(env, bunkerUrl, cUrl);
    return goStringToJstring(env, result);
}

JNIEXPORT void JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46Disconnect(JNIEnv *env, jobject thiz) {
    NIP46DisconnectC();
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46SignEvent(JNIEnv *env, jobject thiz, jstring eventJson) {
    const char *cJson = GET_CSTR(env, eventJson);
    char *result = NIP46SignEventC((char*)cJson);
    REL_CSTR(env, eventJson, cJson);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46GetPublicKey(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, NIP46GetPublicKeyC());
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46NIP44Encrypt(JNIEnv *env, jobject thiz,
        jstring targetPubkey, jstring plaintext) {
    const char *cPk = GET_CSTR(env, targetPubkey);
    const char *cPt = GET_CSTR(env, plaintext);
    char *result = NIP46NIP44EncryptC((char*)cPk, (char*)cPt);
    REL_CSTR(env, targetPubkey, cPk);
    REL_CSTR(env, plaintext, cPt);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46NIP44Decrypt(JNIEnv *env, jobject thiz,
        jstring targetPubkey, jstring ciphertext) {
    const char *cPk = GET_CSTR(env, targetPubkey);
    const char *cCt = GET_CSTR(env, ciphertext);
    char *result = NIP46NIP44DecryptC((char*)cPk, (char*)cCt);
    REL_CSTR(env, targetPubkey, cPk);
    REL_CSTR(env, ciphertext, cCt);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46NIP04Encrypt(JNIEnv *env, jobject thiz,
        jstring targetPubkey, jstring plaintext) {
    const char *cPk = GET_CSTR(env, targetPubkey);
    const char *cPt = GET_CSTR(env, plaintext);
    char *result = NIP46NIP04EncryptC((char*)cPk, (char*)cPt);
    REL_CSTR(env, targetPubkey, cPk);
    REL_CSTR(env, plaintext, cPt);
    return goStringToJstring(env, result);
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46NIP04Decrypt(JNIEnv *env, jobject thiz,
        jstring targetPubkey, jstring ciphertext) {
    const char *cPk = GET_CSTR(env, targetPubkey);
    const char *cCt = GET_CSTR(env, ciphertext);
    char *result = NIP46NIP04DecryptC((char*)cPk, (char*)cCt);
    REL_CSTR(env, targetPubkey, cPk);
    REL_CSTR(env, ciphertext, cCt);
    return goStringToJstring(env, result);
}

JNIEXPORT jint JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46Ping(JNIEnv *env, jobject thiz) {
    return NIP46PingC();
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_nip46GetPendingAuthUrl(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, NIP46GetPendingAuthURLC());
}

// ---- DVM ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_computePopularNotes(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, ComputePopularNotesC());
}

// ---- Import log bridge ----

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_getImportLog(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, GetImportLogC());
}

JNIEXPORT jstring JNICALL
Java_com_nostrvault_relay_HavenBridge_getNotifyLog(JNIEnv *env, jobject thiz) {
    return goStringToJstring(env, GetNotifyLogC());
}
