package com.nostrvault.service

import android.content.Context

/**
 * Keys generated by setup on this device that have not published a follow
 * list yet. Such a key cannot have a kind 3 anywhere, so "no list found" is
 * the truth, not a relay that hasn't answered. Without it one silent relay
 * leaves a new account unable to follow anyone (the follow is queued) and
 * the Fill your feed guide never starts. Cleared on the first publish.
 * iOS: FreshAccountKeys.swift.
 */
object FreshAccountKeys {
    private const val PREFS = "fresh_account_keys"
    private const val KEY = "keys"

    private fun prefs(context: Context) = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    fun mark(context: Context, hex: String) {
        if (hex.isEmpty()) return
        val keys = prefs(context).getStringSet(KEY, emptySet()).orEmpty() + hex
        prefs(context).edit().putStringSet(KEY, keys).apply()
    }

    fun isFresh(context: Context, hex: String): Boolean =
        hex.isNotEmpty() && hex in prefs(context).getStringSet(KEY, emptySet()).orEmpty()

    fun clear(context: Context, hex: String) {
        val keys = prefs(context).getStringSet(KEY, emptySet()).orEmpty()
        if (hex in keys) prefs(context).edit().putStringSet(KEY, keys - hex).apply()
    }
}
