import Foundation

/// Keys generated by setup on this device that have not published a follow
/// list yet. Such a key cannot have a kind 3 anywhere, so "no list found"
/// is the truth, not a relay that hasn't answered. Cleared on the first
/// publish, after which a missing list means the relays lost it.
enum FreshAccountKeys {
    private static let key = "freshAccountKeys"

    static func mark(_ hex: String, defaults: UserDefaults = .standard) {
        guard !hex.isEmpty else { return }
        var keys = Set(defaults.stringArray(forKey: key) ?? [])
        keys.insert(hex)
        defaults.set(Array(keys), forKey: key)
    }

    static func isFresh(_ hex: String, defaults: UserDefaults = .standard) -> Bool {
        !hex.isEmpty && (defaults.stringArray(forKey: key) ?? []).contains(hex)
    }

    static func clear(_ hex: String, defaults: UserDefaults = .standard) {
        guard var keys = defaults.stringArray(forKey: key), let index = keys.firstIndex(of: hex) else { return }
        keys.remove(at: index)
        defaults.set(keys, forKey: key)
    }
}
